### PR TITLE
Autocomplete

### PR DESCRIPTION
**Pull request by AlexGGGG**
Hello and how to include employee list on the main page of the user why that it is not displayed

### CODE REVIEW

**Comment by AIdjIO** [comment]
Hi Aleksandr,
I had implemented the autocomplete on the frontend in the firstname lastname input field.
it was a hardcoded list of names in javascript but because it was for my workplace and because of security concerns i had to remove this feature. the thought was to improve user experience. ultimately what i wanted was to use a badge reader instead that means i need a user table and registration page,etc. I can upload back the auto complete with dummy names for demo. I also made several other changes which are not in the repository because of workplace requirement like visitors need to go through some "powerpoint" slides and confirm they read through them in order to be allowed in, etc.

Sent from ProtonMail mobile

-------- Original Message --------

**Comment by AlexGGGG** [comment]
Good afternoon, if you have a possibility to load as was with the list of workers it would be very quite good, I shall wait. The working version.

**Comment by AlexGGGG** [comment]
You have removed a branch, and that to me to do I do not see the list of employees in your work

**Comment by AIdjIO** [comment]
Hi Alex, i will put the feature in the master branch

**Comment by AlexGGGG** [comment]
ok im waiting, please as soon as possible

**Comment by AIdjIO** [comment]
you can find the added feature at:
https://github.com/AIdjIO/PHP_Covid_Check_In
you can update the list of name in form.php at line 80 and 81
would be better to have this on the backend instead with some AJAX request
but that is a first intent for now

**Comment by AIdjIO** [comment]
> ok im waiting, please as soon as possible

you can find the added feature at:
https://github.com/AIdjIO/PHP_Covid_Check_In
you can update the list of name in form.php at line 80 and 81
would be better to have this on the backend instead with some AJAX request
but that is a first intent for now

**Pull request closed without merging**
